version: '3.2'

services:
  client:
    image: tmeller/parserchainer-client:0.0.32-test
    ports:
      - 4200:4200
    depends_on:
      - restservice
    environment:
      REST_URL: "restservice:3000"
  restservice:
    image: tmeller/parserchainer-restservice:0.0.32-test
    ports:
      - 3000:3000
