version: '3.2'

services:
  client:
    build: ./frontend/parser-chains-client
    ports: 
      - 4200:4200
    depends_on: 
      - restservice
    environment: 
      REST_URL: "restservice:3000"
  restservice:
    build: ./backend
    ports: 
      - 3000:3000
    environment:
      LOGGING_LEVEL_COM_CLOUDERA_PARSERCHAINS: "DEBUG"
      CONFIG_PATH: "/data"
    volumes:
      - /tmp/parser-chains:/data
